### ISSUE TITLE
LIME for survival

### ISSUE THREAD

**Issue by edvbb** [thomasp85/lime#108]
Help me, please
I try to apply LIME for survival analysis in R.
First i make a model_type
```
model_type.surv <- function(x, ...) {
  return("survival")
}
```
then i write a function and I think this function is not correct
```
predict_model.surv = function(x, newdata, type, ...) {
  # Функция показывает, что мы хотим получить числовую переменную в качестве прогноза 
  
  pred = predict(x, newdata, type ='response') # response
  
  return(pred)
}
```
then 

```
library(lime)  
explainer <- lime(data, model)

model
Call:
survival::coxph(formula = f, data = data, ties = "exact", iter.max = 89L, 
    outer.max = 16L)
```
and after 
`explanation = explain(newdudes, explainer)`
i get
`Error: The class of model must have a model_type method. See ?model_type to get an overview of models supported out of the box
`
what must I change in my model? I guess I must change `type ='response'` but I don't know what kind of type to use

**Comment by thomasp85** [comment]
lime only support classification and regression, so `model_type()` should return one of these. If the model cannot be considered either of these types it will not work with lime
