### ISSUE TITLE
explain function throws error for xgboost

### ISSUE THREAD

**Issue by MarcusCramer91** [thomasp85/lime#109]
Hey,

the explain function throws an error "error in strsplit - non character argument" when given an xgboost model object. The issue lies with model_type(xgbmodel), so I am not sure whether this is an issue with lime or xgboost itself. 

MWE:

```r
library(xgboost)
library(lime)
data(biopsy)

biopsy$ID <- NULL
biopsy <- na.omit(biopsy)
names(biopsy) <- c('clump thickness', 'uniformity of cell size', 
                   'uniformity of cell shape', 'marginal adhesion',
                   'single epithelial cell size', 'bare nuclei', 
                   'bland chromatin', 'normal nucleoli', 'mitoses',
                   'class')

set.seed(4)
test_set <- sample(seq_len(nrow(biopsy)), 4)
prediction <- biopsy$class
biopsy$class <- NULL
model <- xgboost(data.matrix(biopsy[-test_set, ]), prediction[-test_set], nrounds = 100)
model_type(model)

explainer <- lime(biopsy[-test_set,], model, bin_continuous = TRUE, quantile_bins = FALSE)
explanation <- explain(biopsy[test_set, ], explainer, n_labels = 1, n_features = 4)
```

**Comment by DeanLeeFumu** [comment]
I  got the same problem here

when I import my pre-trained model and run the explanation

This message occored:

Error in strsplit(obj, ":") : non-character argument

**Comment by Tazinho** [comment]
I got the same problem. However, if you need the model in R (i.e. to use LIME) the workaround `saveRDS()` and `readRDS()` works for me.

**Comment by DeanLeeFumu** [comment]
So I wrapped it up with as_classifier(model) and it worked.
but still not sure it works as xgbooster or just any other classifier. 

I'm new to this package and figuring out how to use it.

**Comment by Tazinho** [comment]
I don’t know as_classifier(), but it sounds like u could easily check if the predictions before and after wrapping stay the same.

**Comment by thomasp85** [comment]
`as_classifier()` simply makes it explicit that the model is a classifier. It is needed if the model object cannot tell it itself...

Anyway, this is an error in `lime` as it assumed the objective was always stored with the model object

**Comment by nielsenmarkus11** [comment]
@thomasp85 , your fix for this seems to override my model being a classification model...
`if (!is.null(obj)) return('regression')`  essentially forces it to be a regression model even if there is a binary objective. In my case the objective is `'binary:logistic'`.  See example below:
```
library(MASS)
library(lime)
data(biopsy)

library(xgboost)

# First we'll clean up the data a bit
biopsy$ID <- NULL
biopsy <- na.omit(biopsy)
names(biopsy) <- c('clump thickness', 'uniformity of cell size', 
                   'uniformity of cell shape', 'marginal adhesion',
                   'single epithelial cell size', 'bare nuclei', 
                   'bland chromatin', 'normal nucleoli', 'mitoses',
                   'class')



# Now we'll fit a linear discriminant model on all but 4 cases
set.seed(4)
test_set <- sample(seq_len(nrow(biopsy)), 30)
prediction <- ifelse(biopsy$class=='malignant',1,0)
biopsy$class <- NULL
X <- model.matrix(~.-1, data=biopsy[-test_set, ])

xgb_train = xgb.DMatrix(data=X, label=prediction[-test_set])
model <- xgboost(data = xgb_train, nrounds = 50, objective = "binary:logistic", verbose = 0)

explainer <- lime(as.data.frame(X), model)
newX <- model.matrix(~.-1, data=biopsy[test_set, ])
explanation <- explain(as.data.frame(newX), explainer, labels=1, n_features = 5, feature_select = "lasso_path")
```

**Comment by thomasp85** [comment]
Oh, damn - that `!` shouldn't be there

thanks

**Comment by thomasp85** [comment]
Should be fixed now
