### ISSUE TITLE
lime do error message 'no applicable method for 'explain' applied to an object of class "factor"'

### ISSUE THREAD

**Issue by YongKyeom** [thomasp85/lime#115]
I sovle my problem.
There is a little some mistake. 
Thank you

**Comment by YongKyeom** [comment]
Now, I upgrade R version to 3.5.1 and try again.
Howver there is same error message...

**Comment by henry090** [comment]
Hi, unload dplyr and lime, then load Lime, again.  Plus, write code in the following form: lime::explain.
