### ISSUE TITLE
LIME development version from GitHub

### ISSUE THREAD

**Issue by henry090** [thomasp85/lime#117]
Hi @thomasp85 
I have several problems with Lime.

1.  After this [solution](https://github.com/rstudio/keras/issues/447) LIME (plot_features) does not give factors for outcome variable (for example: labels = 'Yes', 'No') as 'No' and 'Yes', instead of them I get '1' and '2'. This problem is actual for Keras.
2. Today I have used Lime for h2o **automl**  and when I specify ' bin_continuous' as TRUE, I get the explanation of continuous  variables. What about the rest of data... 
<img width="1274" alt="screen shot 2018-08-06 at 2 12 13 pm" src="https://user-images.githubusercontent.com/38523699/43711226-0f6f7d66-9983-11e8-9eaa-bcb23998babd.png">

**Comment by thomasp85** [comment]
Can I get you to provide a reproducible example?

**Comment by henry090** [comment]
Hi @thomasp85 , please, close this issue. I will open another one later with a reproducible example.
