### ISSUE TITLE
trouble in run explainer

### ISSUE THREAD

**Issue by giancarlomirmillo** [thomasp85/lime#124]
when I try to run explainer on your code, the one I use for understand how LIME works i get this warning:
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'Dropout' object has no attribute 'activation'

which I cannot solve by myself,

thanks for any help

giancarlo

**Comment by thomasp85** [comment]
Can I get you to try again with the GitHub version - It may already be fixed...
