### ISSUE TITLE
Example from blog post no longer works

### ISSUE THREAD

**Issue by jeroen** [thomasp85/lime#127]
Moved from https://github.com/rstudio/keras/issues/563: I can no longer reproduce [this rmd post](https://raw.githubusercontent.com/thomasp85/data_imaginist/master/content/post/2018-03-06-lime-v0-4-the-kitten-picture-edition.Rmd) with the dev version of lime. The `explain()` function I errors with:  **Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (1505280, 1)**.

I also tried downgrading `lime` to the CRAN version, which does not raises this error, however instead `explain()` seems to freeze.

**Comment by thomasp85** [comment]
OMG, I've made something stupid here...
