### ISSUE TITLE
Add ranger to lime

### ISSUE THREAD

**Issue by nielsenmarkus11** [thomasp85/lime#130]
It would be nice to add ranger models to lime.  I've got some un-generalized code that I could tweak to add this into the package.

**Comment by thomasp85** [comment]
I would welcome a PR - look at `models.R` for the preferred format:

https://github.com/thomasp85/lime/blob/2f88098097abb25344338c9c9418e392b132572b/R/models.R#L106-L259

**Comment by nielsenmarkus11** [comment]
@thomasp85  - I added the pull request here: https://github.com/thomasp85/lime/pull/131
