### ISSUE TITLE
Font family not found in Windows font database

### ISSUE THREAD

**Issue by indrajitsg** [thomasp85/lime#14]
Hi Thomas,

I am trying to use your lime package and whenever I am running the **plot_features** function, I get the following warning in R console multiple times:
`Warning messages:`
`1: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,   : font family not found in Windows font database`

I get same warning around 8 to 10 times. Is there some specific font that you are using only available in Linux machine?

It would great if you can suggest a workaround or change this in the code. The warnings are a bit annoying.

Regards,

**Comment by pommedeterresautee** [comment]
this is a ggplot2 issue.
Did you tried https://stackoverflow.com/questions/14733732/cant-change-fonts-in-ggplot-geom-text ?

**Comment by thomasp85** [comment]
I've removed 'Arial Narrow' because it seems to be less prevalent than I thought...
