### ISSUE TITLE
Bug for R^2

### ISSUE THREAD

**Issue by Make42** [thomasp85/lime#148]
There seems to be a bug in `R/lime.R`. In line 52
```
r2 <- fit$deviance / fit$null.deviance
```
but in line 60
```
r2 <- fit$dev.ratio
```
where `dev.ratio=1-dev/nulldev` according to `?glmnet`. So in the case of line 52 a 0 would be a perfect fit, while in line 60 a 1 would be perfect fit. This should be consistent!

**Comment by pkopper** [comment]
#156 and #157 deal with this issue in more detail.

**Comment by Make42** [comment]
Also, please mention, once this fix is pushed to cran.

**Comment by thomasp85** [comment]
Should get on CRAN this week
