### ISSUE TITLE
Gower distance tends to fit global model

### ISSUE THREAD

**Issue by pkopper** [thomasp85/lime#158]
I experienced a practical problem when using Gower's distance as a dissimilarity measure. In many different settings, the resulting model was very global. This is - to my mind - because when using Gower's distance we do not work with a kernel function. This can be argued to be meaningful as Gower's distance 'scales' the resulting dissimilarities already. However, practically I have observed in some settings that the resulting dissimilarities are not very discriminating so that we end up with an explainer which is not that different from a global explainer.
Did someone else make similar observations and does someone have a good solution for working with mixed data?
I found the distance measure (eq. 9) from the article below very helpful in different contexts. However, the use of it would require to change to package code.
http://www.cs.ust.hk/~qyang/Teaching/537/Papers/huang98extensions.pdf

**Comment by thomasp85** [comment]
It might make sense to allow a kernel on top of the Gower distance as well...

**Comment by pkopper** [comment]
If you want to I can suggest a fix via pull request.

**Comment by thomasp85** [comment]
Thank you — that would be welcome
