### ISSUE TITLE
Dependenct on tibble

### ISSUE THREAD

**Issue by pommedeterresautee** [thomasp85/lime#17]
I noticed that `tibble` is just used at onece in the source code and may be easily replaced by a data.frame call.
Do we need a dependency on it?
https://github.com/thomasp85/lime/blob/71521e80daaca6255f99b440ebbef6de77eab0aa/R/lime.R#L84

**Comment by thomasp85** [comment]
I've opted for it as `tibble` is very lightweight and it makes the output much nicer. I can live with removing it but I can't see much gain in it?

**Comment by pommedeterresautee** [comment]
we can close
