### ISSUE TITLE
Remove dependency on dplyr

### ISSUE THREAD

**Issue by pommedeterresautee** [thomasp85/lime#19]
We are using only `bind_rows` function from dplyr. May be we want to replace it by a rbind call.
`df <- Reduce(rbind, listOfDataFrames)`
`do.call("rbind",listOfDataFrames)`

**Comment by thomasp85** [comment]
You're right - I'll do that

**Comment by thomasp85** [comment]
(Never use `Reduce` for this! 🙂)
