### ISSUE TITLE
Dependency on maggritr and purr

### ISSUE THREAD

**Issue by pommedeterresautee** [thomasp85/lime#20]
For comfort reasons only I have heavily used these two packages.
I can easily remove them, it will make the code less readable and longer.

However, we have too many dependencies right now, and the package is still small. Some of them will probably break in the future (Harvey packages have beautiful API but a tendency to evolve in the long term) and so on... (it also explains why I want to remove the other dependencies).

So, what do you think about cleaning the package?
It may happen after the change the API you have planned.

**Comment by thomasp85** [comment]
I never really use magrittr and purrr (and very seldom dplyr - I was apparently lazy here) when developing packages.

I accepted that you wanted to use pipe and purrr, but if you want to remove them from your code I'll be very supportive.

I think the notion of "too many dependencies" is a bit strange though - if a package is used for a valid reason I have no problem including it. If you are more comfortable programming with purrr, I think that's a valid reason...

**Comment by thomasp85** [comment]
I currently maintain ~15 packages and seldom have problems with changing API's (just to share my personal experience). I have no problem removing `tibble` and your point is valid so consider that done. I would be thrilled if you removed pipe use in the text-explainer as I prefer its use during analysis and not within packages, but being a collaboration I am also OK with others using their preferred approach. The same goes for purrr.

**Comment by pommedeterresautee** [comment]
done/closing
