### ISSUE TITLE
Explain README sentence

### ISSUE THREAD

**Issue by pommedeterresautee** [thomasp85/lime#26]
I am not sure to understand the sentence : `The global model explanation using submodular picks is not supported in either packages.`
Can we make it more clear? Add context?
(I imagine it s related to generalizing the methodology but I am not sure)

**Comment by thomasp85** [comment]
It's a throwback to a discussion in the LIME article... Maybe we should just remove it as most people will not read the article anyway...

**Comment by thomasp85** [comment]
The gist of it is that the article discusses a sampling approach that selects representative observations that, when explained with lime, gives an explanation of the model at a global, rather than local, scale...
