### ISSUE TITLE
Error: assert_that: assertion must return a logical value

### ISSUE THREAD

**Issue by navaneesh007** [thomasp85/lime#34]
# Kindly request you to priority this  

library(MASS)
library(lime)
iris_test <- iris[1, 1:4]
iris_train <- iris[-1, 1:4]
iris_lab <- iris[[5]][-1]
model <- lda(iris_train, iris_lab)
explanation <- lime(iris_train, model)
explain(iris_test, explanation, n_labels = 1, n_features = 2)

R 3.3.2 64-bit
Lime 0.3.0

When I have seen trace-back 

![image](https://user-images.githubusercontent.com/13904363/30567578-ad74c04e-9cee-11e7-92ba-63df7039a6b3.png)

This one is only for example that 'explain'  function of lime is not working in my system .I have similar work which require 'explain' function of lime and giving same parameter and thrown up with similar  

Error: assert_that: assertion must return a logical value

assert_that(is.null(labels) + is.null(n_labels) == 1, msg = "You need to choose between labels and n_labels parameters.") 

# Thanks in Advance

**Comment by thomasp85** [comment]
Can I get you to try it out with the latest GitHub version? I cannot reproduce the error...

**Comment by jessiezz-gmaira** [comment]
I am having the same issue with the explain function using the Iris dataset and my own dataset using the 0.20 version from RCRAN.   I've been attempting to download the latest github version but now see the following error upon download:

ERROR: dependency 'Rcpp' is not available for package 'lime'
* removing 'C:/Users/gisselle.maira/Documents/R/win-library/3.3/lime'
Installation failed: Command failed (1)

**Comment by thomasp85** [comment]
The CRAN version is 0.3.0? Can I get you to install that and then see if you can reproduce it. If you still get the error please post a session info

**Comment by jessiezz-gmaira** [comment]
Re-installing the package seems to have worked for me.  Thanks!

**Comment by AKazlou** [comment]
Had the same issue with the 0.3.0 version from CRAN, re-installing did help. Thanks!
