### ISSUE TITLE
Error in bin_cuts[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by RosebudAnwuri** [thomasp85/lime#41]
Hello Thomas,

Great work you are doing here. I had an error when creating the `explain` object:

`Error in bin_cuts[[i]] : subscript out of bounds`

In my case, I have just one numerical feature to be explain a multiclass lable using a h2o gbm object.

Here is my (non-reproducible) code:

`explainer = lime::lime(trainDF, model = model_gbm, bin_continuous = TRUE)
explanation =explain(test_lime, explainer  = explainer,n_features = 1, n_labels = 10)
`

I could be doing something wrong and would love to find out what it could be. Many thanks.

**Comment by thomasp85** [comment]
Can I get you to install the GitHub version and try again - it should have been addressed...

**Comment by RosebudAnwuri** [comment]
Thanks! It works now
