### ISSUE TITLE
Error when defining custom model_type which returns regression predictions as a data.frame

### ISSUE THREAD

**Issue by KhalimCK** [thomasp85/lime#43]
Hi,

Thank you for your R implementation of lime! I'm keen to implement lime with a custom model I have built. I have defined my predict_model and model_type functions as recommended within the help pages, however, when using them in conjunction with the lime and explain functions I receive the error: 

Error in y[1, ] : incorrect number of dimensions

The code I'm running is simply:

explanation <- lime(data.frame(train), model)
out <- explain(test, explanation, n_labels = 1, n_features = 2, n_permutations = 1000, feature_select = "highest_weights")

My problem is a regression problem and the issue seems to be triggered by the n_labels with a regression problem but I can't run anything unless I set either that parameter or the labels parameter. The issue arises within explain.data.frame, during the construction of the res object, 

When the object case_res is created, it appears to be done so via a call to the predict_model function I have defined. As default, the predict function returns a data frame with a single column of the regression predictions. In the call to model_permutations, it passes case_res[i, ] as the y argument and at this stage it converts it to a vector, whereby the code fails as model_permutations seems to be looking for a data frame in the line: 

Do you have any recommendations regarding what the output of my predict function should specifically look like, or if there is anything glaringly obvious with how I'm attempting to implement the custom function. My predict_model and model_type functions are included below. I'm afraid I can't provide any more specific details of the attributes of the model itself.

Kind regards,
Khalim

predict_model.model <- function(x, newdata, type = "raw", ...) {
  res <- data.frame(predict(x= x, newdata = newdata, ...))

  switch(
    type,
    raw = data.frame(Response = res, stringsAsFactors = FALSE),
    prob = as.data.frame(res$posterior, check.names = FALSE)
  )
}

model_type.model <- function(x, ...){
  'regression'
}

**Comment by thomasp85** [comment]
This is a bug in the CRAN version and should have been fixed. Can I get you to install the GitHub version and confirm?

**Comment by KhalimCK** [comment]
You are correct, thanks! My implementation works.
