### ISSUE TITLE
Error in UseMethod("explain") :    no applicable method for 'explain' applied to an object of class "character"

### ISSUE THREAD

**Issue by AMANSINGHPRO** [thomasp85/lime#48]
Hi,
I am new to LIME. I ran example("LIME") got the error "Error in UseMethod("explain") : 
  no applicable method for 'explain' applied to an object of class "character" ". Not sure what I am doing wrong. Please help. Thanks

**Comment by AMANSINGHPRO** [comment]
OH. Got it. explain function I had was masked from dplyr not from lime. I restarted the session without including dplyr package and works fine now. Thanks for the amazing package gonna play with it now. :)

**Comment by prokopyev** [comment]
Great, that solved my problem too.
