### ISSUE TITLE
Error in y[1, ] : incorrect number of dimensions

### ISSUE THREAD

**Issue by ssobel** [thomasp85/lime#49]
Hello, I think the lime methodology and package are great. But I am getting the error "Error in y[1, ] : incorrect number of dimensions" when I try to use lime on a randomForest model. Here is my code and error:

I think the issue is how I am defining "predict_model.randomForest" but not sure how to fix the "y[1, ]" error. Help would be very much appreciated. Thank you.

```
library(lime)
library(randomForest)
library(MASS)

model <- randomForest(medv ~ ., data = Boston, keep.forest = TRUE)

predict_model.randomForest <- function(x, newdata, type, ...) {
  res <- predict(x, newdata = newdata, type = ifelse(type == "raw", "response", type))
  switch(type,
         raw = data.frame(Response = res, stringsAsFactors = FALSE),
         prob = as.data.frame(res, check.names = FALSE)
  )
}

model_type.randomForest <- function(x, ...) "regression"

explanation <- lime(Boston[, 1:13], model)
explanations <- explain(Boston[1:5, 1:13], explanation, n_features = 3, n_labels = 1)

**Error in y[1, ] : incorrect number of dimensions**
```

**Comment by thomasp85** [comment]
Hi

I cannot reproduce your error on my system. Can you install the latest version from GitHub and see if it solves it (you'll get a warning about not using `n_labels` with regression models)

Another comment is to pass the full training data to the `lime` function. It is used to record the feature space so it should not be truncated...

**Comment by ssobel** [comment]
Hi Thomas, I installed the latest version from GitHub and passed the full training data to the lime function but still am getting the same error. Can you post the exact code that works on your system for using lime on the Boston data set using randomForest? Thank you.

**Comment by thomasp85** [comment]
My apologies for confusing you with the truncation of the data - you were doing it correctly before and I misread it as you were only using the first 13 rows (not cols)

Still, running the exact same code as it appears in your first post does not raise any errors. I've attached a plot of the results below
![rplot](https://user-images.githubusercontent.com/1775316/32786062-443b26c2-c953-11e7-9e83-12ff5a211c06.png)

**Comment by ssobel** [comment]
Hi Thomas, I tried again but still to no avail. Do you mind posting code that I should use (Boston dataset, randomforest) for modeling in the mlr package? Thank you.

**Comment by thomasp85** [comment]
I have little experience with mlr so you’ll be just as capable as me. Still, your code works and my machine, so I’m pretty sure it is a problem on your setup. Can I get you to restart your r session run your code and give me a `sessionInfo()` dump

**Comment by ssobel** [comment]
Hi Thomas, based on the sessionInfo() dump I see that I was running R version 3.4.0. I upgraded to R 3.4.2 and reinstalled lime from GitHub. Then it failed saying there is no package called 'curl' so I installed curl, then installed lime again, then ran the code above and it seems to work now.

Thank you for your help!

Take care.
