### ISSUE TITLE
scope of lime package in R 

### ISSUE THREAD

**Issue by negyn** [thomasp85/lime#5]
Hi, thank you for LIME package, it is so interesting for me.
I have some questions, it seems to me that the current version of LIME package in R doesn't support the text and image data, is it right? so, except random forest what other kinds of classifier does it support?

**Comment by pommedeterresautee** [comment]
Regarding the text support I am working on it.
Regarding the algo supported (for explanation) anything which works with predict is supported.

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
https://github.com/thomasp85/lime/pull/6
