### ISSUE TITLE
Error using H2O xgboost model

### ISSUE THREAD

**Issue by dkincaid** [thomasp85/lime#50]
Opening this new issue as requested in issue #40. 

When using `lime::explain` with the H2O xgboost model it throws the following error:

```
Error: java.lang.IllegalArgumentException: Given domain has 0 classes, but predictions have 3 columns (per-class probabilities) for multinomial metrics.
```

Here is a reproducible example using the Iris dataset:
```r
library(h2o)
h2o.init()

# First show that it's successful without any missing data
full_iris_frame <- as.h2o(iris)
full_mdl <- h2o.xgboost(training_frame = full_iris_frame, y = "Species")

full_explainer <- lime::lime(dplyr::select(as.data.frame(full_iris_frame), -Species), full_mdl)

full_explanation <- lime::explain(dplyr::select(as.data.frame(full_iris_frame)[1:4,], -Species),
                             full_explainer, n_labels = 3 , n_features = 3)
```

**Comment by thomasp85** [comment]
This doesn't really have anything to do with lime - if you run:

```r
h2o.predict(full_mdl, as.h2o(dplyr::select(as.data.frame(full_iris_frame)[1:4,], -Species)))
```

you get the same error. I'm afraid I can help you more here as my experience with H2O is rather low. Maybe @mdancho84 can chime in..?

**Comment by mdancho84** [comment]
@dkincaid - Let me work @dvaughan on this. For some reason h2o.xgboost is not available on Windows, and I’m a PC guy (although probably switching). 

@thomasp85 - your going to be getting a bunch of H2O questions. I’ll be speaking at H2O World in December about your pkg. Just an FYI.

**Comment by thomasp85** [comment]
I think it would be beneficial to move this discussion to the H2O repo as it is no longer lime related (I simply thought @mdancho84 had a quick resolution)

**Comment by mdancho84** [comment]
I agree. Not a simple solution, and it likely pertains to the h2o.xgboost algorithm.
