### ISSUE TITLE
Lime Error in y[1, ] incorrect number of dimensions

### ISSUE THREAD

**Issue by steviebear** [thomasp85/lime#55]
Hi

Sorry in advance as I expect this is a daft error on my behalf, but I keep getting an incorrect number of dimensions error. Code:

library(caret)
library(lime)
x = runif(100)
y = runif(100)
traindata = data.frame(x,y)
x = runif(100)
y = runif(100)
testdata = data.frame(x,y)
summary(testdata)
model <- train(y ~ x, data = traindata,method = 'lm')
summary(model)
prediction <- predict(model,testdata)
table(prediction,testdata$y)
explainer <-lime(traindata,model)
explanation <-explain(testdata,explainer,labels = c('x'),n_features = 2)
-------
Error in y[1, ] : incorrect number of dimensions
In addition: Warning message:
In explain.data.frame(testdata, explainer, labels = c("x"), n_features = 2) :
  "labels" and "n_labels" arguments are ignored when explaining regression models

**Comment by thomasp85** [comment]
Have you updated lime? This looks like a bug in an earlier version?

**Comment by steviebear** [comment]
Yes, that managed to solve it, Thanks :-)
