### ISSUE TITLE
Support for time series recurrent neuronal networks

### ISSUE THREAD

**Issue by Tazinho** [thomasp85/lime#62]
Hi @thomasp85 thanks for this super nice package!
I hope it is appropriate to ask a quick question here.?

Does your implementation already support explainers for time series recurrent neuronal networks?
I am a bit new to keras and lime in R. But this usecase would make it quite attractive to dive a bit deeper into this.

**Comment by expectopatronum** [comment]
Hi @Tazinho! The M in lime stands for 'model_agnostic', so theoretically all models are supported. What you problaby have to do is to implement methods `predict_model.your_model_name` and `model_type.your_model_name` to make it work. Check out how it's done in [models.R](https://github.com/thomasp85/lime/blob/master/R/models.R). 
If you need support for image, this is [currently work in progress](https://github.com/thomasp85/lime/issues/35).

**Comment by pommedeterresautee** [comment]
Right now Lime is good at classification task. You will also need to formulate the prediction in a way which match the Lime spirit. As said by @expectopatronum it s model agnostic.
