### ISSUE TITLE
can not install lime package under linux system

### ISSUE THREAD

**Issue by keycai** [thomasp85/lime#64]
permutations.cpp: In function ‘Rcpp::List get_index_permutations(Rcpp::IntegerVector, int)’:
permutations.cpp:15:80: error: ‘sample’ was not declared in this scope
   IntegerVector nb = sample(original_document.size(), number_permutations, true);
                                                                                ^
make: *** [permutations.o] Error 1
ERROR: compilation failed for package ‘lime’

**Comment by pommedeterresautee** [comment]
What is your R version / Rcpp version ?

**Comment by thomasp85** [comment]
I'm closing this - if you still have a problem, please reopen and provide the requested information
