### ISSUE TITLE
lime::lime error

### ISSUE THREAD

**Issue by patarol** [thomasp85/lime#67]
Hi, 

I'm running a `lgb.train` model and when I do it with `iris` data I have no problems to run `lime` function. However, when I use my dataset (~50k observations and 115 variables) I get the following error:

```
# Error in cut.default(x[[i]], unique(explainer$bin_cuts[[i]]), labels = FALSE,  : 
  invalid number of intervals
```
I tried to run line by line from function's code , but I have no clues.
My target variable is binary (0 and 1) and all my dataset is numeric.

my code is:

```
model <- lgb.train(data = train, 
                   label = target,
                   obj = "binary", 
                   eval = "binary_logloss",
                   nrounds = 100,
                   early_stopping = 100)

expl <- lime(train, model)
```
I also tried to transform `train` into a `data.frame`, no lucky though.                   

P.S.: my dataset is too larget to put it here,

**Comment by thomasp85** [comment]
My guess is that you have a feature with zero variance which then can't be cut... Can you try to look into that?

**Comment by thomasp85** [comment]
Closing - reopen if new information becomes available
