### ISSUE TITLE
explaining rpart

### ISSUE THREAD

**Issue by schadd** [thomasp85/lime#7]
Hello,

I am currently trying out your library since I think it would be great if one could use lime in R. However when using rpart I am getting a weird error. Here is the code to reproduce it:

iris_test <- iris[52, 1:4]
iris_train <- iris[-(52), 1:4]
iris_lab <- iris[[5]][-(52)]
rpart_train <- iris[-(52),]

_#I want to explain the 52nd row of the dataset_

model <- rpart(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
               data = rpart_train,
               method='class')

explain <- lime(iris_train, model, bin_continuous = TRUE, n_bins = 5)
explanation <- explain(iris_test, n_labels = 2, n_features = 3)

when I run the last line, I get the following error:

Error in `$<-.data.frame`(`*tmp*`, "case", value = "52") : 
  replacement has 1 row, data has 0
In addition: Warning messages:
1: Unknown or uninitialised column: 'feature'. 
2: Unknown or uninitialised column: 'feature'.

I'm not sure whether it's because I am doing something wrong since I am fairly new in R or whether it's an actual issue.

**Comment by pommedeterresautee** [comment]
Can you try using rpart through Caret package and report your results?

**Comment by schadd** [comment]
When I use caret with rpart as method then it doesn't show an error.

**Comment by pommedeterresautee** [comment]
Basically, results returned by Caret are wrap in a data.frame and the LIME package expects such data.frame.
I ve understood @thomasp85 is thinking to a general way to manage that point, in between you can use caret.

**Comment by thomasp85** [comment]
The CRAN release allows support of arbitrary models. See `?model_support`
