### ISSUE TITLE
Unknown feature Error for logical column type

### ISSUE THREAD

**Issue by rpatel3105** [thomasp85/lime#75]
Error: Unknown feature type for logical column. 
I am getting above error for all logical columns in my data. Your input will be highly appreciated for this issue.

I have checked dataframe.R for lime package but was not able to find condition for is.logical.

**Comment by thomasp85** [comment]
Can I get you to provide a reproducible example

**Comment by rpatel3105** [comment]
library(caret)
library(lime)

# Split up the data set
iris$Sepal.Length <- sample(c(TRUE,FALSE), 150, TRUE)

iris$Sepal.Length <- as.logical(iris$Sepal.Length)
iris_test <- iris[1:5, 1:4]
iris_train <- iris[-(1:5), 1:4]
iris_lab <- iris[[5]][-(1:5)]

# Create Random Forest model on iris data
model <- train(iris_train, iris_lab, method = 'rf')

# Create an explainer object
explainer <- lime(iris_train, model)

# Explain new observation
explanation <- explain(iris_test, explainer, n_labels = 1, n_features = 4)
