### ISSUE TITLE
Questions on LIME implementation

### ISSUE THREAD

**Issue by rajafan** [thomasp85/lime#88]
Dear Thomas,

Thanks for providing the R package for LIME. I have some doubts regarding to the implementation. It would be nice to have your clarification.

In the vignette, you mentioned that there are 7 key steps for LIME implementation as follows:
1. For each prediction to explain, permute the observation n times.
2. Let the complex model predict the outcome of all permuted observations.
3. Calculate the distance from all permutations to the original observation.
4. Convert the distance to a similarity score.
5. Select m features best describing the complex model outcome from the permuted data.
6. Fit a simple model to the permuted data, explaining the complex model outcome with the m features from the permuted data weighted by its similarity to the original observation.
7. Extract the feature weights from the simple model and use these as explanations for the complex models local behavior.

My question is for Step 6 and 7, could we just build a single elastic net model with alpha = 0.5 and use the variables with the top-m coefficients as explainations? Will the results be different if a LASSO model is built for Step 6 and a RIDGE model is used for Step 7? Of course, I understand that there are many feature selection methods for Step 6. Let's just assume that LASSO is used for Step 6 and RIDGE is used for Step 7. Will the results be the same compared with developing a single ELASTIC NET model with alpha = 0.5?

**Comment by thomasp85** [comment]
I cannot answer you on whether it will be fundamentally different or not (I'm pretty sure it will not be numerically equivalent).

Basically any type of simple model that can take weighted input can be used for the final stage of the LIME approach - if the model comes with automated feature extraction then that could potentially overtake step 5...

None of that is supported in the current iteration of LIME though...

**Comment by thomasp85** [comment]
No - the feature selection and local fitting happens on the same state of the input data (the recoded form). It all happens in the `model_permutations()` function: https://github.com/thomasp85/lime/blob/bda237d8fb643c4f4982e0259e4dd3f5c3269f7c/R/lime.R#L32
