### ISSUE TITLE
x should be a matrix with 2 or more columns eeror when building explanation

### ISSUE THREAD

**Issue by Nadu123** [thomasp85/lime#89]
Hi
I am trying to use lime explanation with Xgboost model using diabetes data set from : 
https://www.kaggle.com/uciml/pima-indians-diabetes-database

my code is 
dat <- read.csv('dd.csv')
dat <- na.omit(dat)

set.seed(3456660)
trainIndex <-  createDataPartition(dat$Class, p = 0.8, list= FALSE)
traini <- dat[trainIndex, ]
testi<- dat[-trainIndex, ]
train_label <- as.matrix(traini$Class)
test_label <- as.matrix(testi$Class)
training <- as.matrix(as.data.frame(traini))
test<- as.matrix(as.data.frame(testi))
dat$class <- NULL

dtrain <- xgb.DMatrix(data = training, label=train_label, missing = 0)
dtest <- xgb.DMatrix(data = test, label=test_label,missing = 0)
watchlist <- list(train=dtrain, test=dtest)

bst <- xgb.train(data=dtrain, max.depth=6, eta=1, nthread = 2, nround=2, watchlist=watchlist, objective = "binary:logistic")

explainer <- lime(traini, model=bst, bin_continuous = TRUE, quantile_bins = FALSE)
explanation <- explain(testi[1:9,] , explainer, n_labels = 1, n_features = 4, kernel_width = .8)

plot_features(explanation,ncol = 1)

When I create the explanation I get the following error : 
_> explanation <- explain(testi[1:9,] , explainer, n_labels = 1, n_features = 4, kernel_width = .8)
Error in glmnet(x[, c(features, j), drop = FALSE], y, weights = weights,  : 
  x should be a matrix with 2 or more columns
>_ 

you support is appreciated

**Comment by kimyenn** [comment]
@Nadu123 Did you ever solve this problem? I am seeing the same error
