### ISSUE TITLE
Display plot_features for specific observations

### ISSUE THREAD

**Issue by allanlc** [thomasp85/lime#95]
Hi Thomas,

I'm new in using LIME and wanted to know how it was possible to display specific plot_features according to a userID.

In fact, in my explanation_df (coming from the exlpain function) I see that my userID is contained in a list in the column "data" of my explanation_df. I do not manage to display these explanations for a specific user.

Is there a way to do it? 

Thanks a lot

**Comment by thomasp85** [comment]
You can simply filter your explanation data.frame to only include the rows you want to plot
